apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-auth
  namespace: bookstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-auth
  template:
    metadata:
      labels:
        app: db-auth
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "password"
            - name: MYSQL_USER
              value: "user"
            - name: MYSQL_PASSWORD
              value: "password"
            - name: MYSQL_DATABASE
              value: "bookstore_auth"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-auth-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-auth-storage
          persistentVolumeClaim:
            claimName: mysql-auth-pvc
