apiVersion: v1
kind: Service
metadata:
  name: bookstore-gateway
  namespace: bookstore
spec:
  type: LoadBalancer
  ports:
    - name: auth
      port: 80
      targetPort: 5001
    - name: catalog
      port: 81
      targetPort: 5002
    - name: purchase
      port: 82
      targetPort: 5003
  selector:
    app: auth-service