apiVersion: v1
kind: Service
metadata:
  name: auth-lb
  namespace: bookstore
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 5001
  selector:
    app: auth-service
