apiVersion: v1
kind: Service
metadata:
  name: catalog-lb
  namespace: bookstore
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 5002
  selector:
    app: catalog-service
