apiVersion: v1
kind: Service
metadata:
  name: purchase-lb
  namespace: bookstore
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 5003
  selector:
    app: purchase-service
