apiVersion: v1
kind: Service
metadata:
  name: purchase-service
  namespace: bookstore
spec:
  type: NodePort
  selector:
    app: purchase-service
  ports:
    - port: 5003
      targetPort: 5003
      nodePort: 30003
